### ISSUE TITLE
Won't work when trying to play a local file

### ISSUE THREAD

**Issue by totoroyyb** [Starz0r/mpv_csharp_uwp#4]
Hi there,
I'm trying to swap the original http address to a local file address from File Picker.
However, it doesn't work. There is nothing showing up. And then I put the original http address in and it works.

I don't why. Please let me know the way of rendering local file.

Thanks!

**Comment by Starz0r** [comment]
Because of UWP's sandboxed nature, you can't just open files on a users computer through fopen without actual permission. There is many ways to get permission, and I believe the File Picker is one of those ways. However, you can't use the normal "loadfile" execute command in this way, unless you are on Windows 10 Redstone 4 and ask the user for complete file system access. libmpv allows you to get around this by writing your own fopen that respects the sandbox. I've already done this in the repository, so the code would be somewhat as follows.

So after the File Picker has finished executing, run this instead of loadfile through ExecuteCommand
```C#
StorageFile your_file_from_file_picker = //put your file from file picker here, must be type StorageFile
streamcb_file = (StorageFile)fileArgs.Files[0]; await Task.Run(() =>
{
     Task<Stream> tmp = streamcb_file.OpenStreamForReadAsync();
     streamcb_stream = tmp.Result;
});

mpv.StreamCbAddReadOnly("buffer", strFilePath, StreamCbOpenFn);
mpv.ExecuteCommand("loadfile", "buffer://fake");

```

This will open the file through a stream buffer instead and will allow you to give the requested bytes to libmpv automatically. Be careful though, since we are now taking practically ownership of the file, you should be aware if the application is 32-bit or 64-bit, as 32-bit programs cannot allocate more than 2GB. Anything more than 2GB will crash the program entirely (or some other undefined behavior) if only compiled for 32-bit.

**Comment by totoroyyb** [comment]
Thanks for your solution. It works now. But I get some questions about the efficiency.

I tested the same .mkv file in my project, ACG and ZPlayer, two of latter are existing player in Microsoft Store. The result is not so good on my project. In my project the CPU fluctuates between 8% - 12%, in ZPlayer 4% - 8%, in ACG 3% - 5%.

I'm wondering whether it's the problem of the solution provided above concerning reading from buffer or the problem around decoding method since I notice the ACG is clearly H/W decode, but not very sure about ZPlayer and my project.

Does mpv automatically enable H/W decoding or not? If not, how to enable it?

Thanks again! Your solution is really helpful!

**Comment by Starz0r** [comment]
Efficiency currently depends on the client computer. libmpv currently has no way to initialize a SwapChainPanel so I have to use ANGLE, which is a OpenGL Abstraction Layer that translates calls to DirectX compatible ones, this can cause some additional overhead depending on GPU Strength.

libmpv has Hardware Decode disabled by default (you can find the reasoning in their documentation). You can enable it from `mpv.SetOptionString` and looking in generated documentation when compiling libmpv.

I should also mention these bindings only support mpv 0.27.x and nothing higher currently. Using a version of libmpv higher than specified might cause issues, or the bindings may not be correct so nothing may work. I'll probably write this down sometime in the near future, and support mpv 0.28.x and higher eventually, but 0.28.x has many breaking changes that I have yet to address.

**Comment by totoroyyb** [comment]
I get another issue when using stream. Playing the first video works perfectly. However, when I was playing the first video, and I try to open the File Picker and reload another video, then thing goes wrong. The program crashed and it seems to cannot reassign the `inputfile` to `streamcb_file` since the computer is working on reading.

            StorageFile inputFile = await OpenFile.LoadFileAsync();

            if (inputFile != null)
            {
                streamcb_file = inputFile;
                await Task.Run(() =>
                {
                    Task<Stream> tmp = streamcb_file.OpenStreamForReadAsync();
                    streamcb_stream = tmp.Result;
                });
                
                mpv.StreamCbAddReadOnly("buffer", streamcb_file.Path, StreamCbOpenFn);
                mpv.ExecuteCommand("loadfile", "buffer://fake");
                VidStatus.SetPauseStatus(false);
            }

So, I've tried to cancel the task and close the stream, but always end in some exception like Task.canceled exception.

Is there any workaround? It should open the new file and replace the old one and play, I think.

Thanks for your help!

**Comment by Starz0r** [comment]
Pretty sure you need to tell libmpv to stop playing whatever is, that way it can prepare properly for a new video to be played. Unfortunately, I can't tell you what command that is offhand because I've never needed to use it before.

It's also a possibility that the asynchronous task that is running on a separate thread isn't getting closed properly (doing this can be different depending on the circumstances).
