### ISSUE TITLE
I need this ...

### ISSUE THREAD

**Issue by Noemata** [Starz0r/mpv_csharp_uwp#5]
There are parts of what you're doing that I need in my UWP project.  Could you please provide some detail on what the C++ side of this looks like.  I'd like to get a clearer picture of how things come together.

**Comment by Starz0r** [comment]
Sorry for the delay on this response.

I'm not a C++ person, so I don't have a lot of ideas, or what to tell you. This library is mostly based on the CSharp libmpv example from the [mpv-examples](https://github.com/mpv-player/mpv-examples) repository. Although it's been much improved since then to be more C# idiomatic.

Is C# interoperable with C++ in a UWP environment? I'm not really sure if you are asking for help getting a working C++ UWP bindings or somehow using this in place of that.
